[package]
name = "tinter"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "ANSI Color output"
keywords = ["ansi", "color"]
repository = "https://github.com/swamp/swamp"

[dependencies]
